### ISSUE TITLE
How to configure an SQS event source for Lambda??

### ISSUE THREAD

**Issue by gajendrabisht** [skawtus/dp-collection-svc#2]
Your lambda expression worked fine but only on invoke triggered manually.
Did you manage to allow some sort of polling / event source for your lambda expression, cause as I understand this is not yet supported by AWS for SQS.... only S3, Dynamo etc.

**Comment by scottleedavis** [comment]
".. you can use CloudTrail to log the requests from SQS to S3, then have changes to S3 trigger the events that can get your Lambda function to respond."

https://news.ycombinator.com/item?id=8602936
